apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-main
  namespace: prometheus
  labels:
    app: example
data:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'email'
    receivers:
    - name: 'email'
      email_configs:
      - to: 'aungdppvrtpgpuhhiz@tpwlb.com'
