apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-prometheus-stack-prometheus
  name: prometheus-nodeport
  namespace: prometheus
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-web
    port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 30909
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: prometheus-kube-prometheus-prometheus
  sessionAffinity: None
  type: NodePort
